version: "3.3"
services:
    mysql:
        image: mysql:5.7.28
        container_name: mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: "America/Sao_Paulo"
        volumes:
            - .docker-volumes/mysql:/var/lib/mysql
            - .setup/build/dev/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        networks:
            - payment-charge

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ""
        networks:
            - payment-charge
    app:
        image: paymentcompany/paymentcharge:latest
        build:
            context: ./
            args:
                NODE_ENV: dev
            dockerfile: .setup/build/dev/Dockerfile
        container_name: "payment-charge"
        volumes:
            - ./:/var/www/localhost/htdocs
        ports:
            - "8080:80"
        links:
            - mysql
        environment:
            - APP_ENV=${APP_ENV:-local}
            - OPCACHE_ENABLE=${OPCACHE_ENABLE:-1}
            - XDEBUG_MODE=${XDEBUG_MODE:-debug}
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
            - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT:-9003}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - payment-charge

    zookeeper:
      image: confluentinc/cp-zookeeper:6.2.4
      container_name: payment-charge-zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
        - payment-charge

    kafka:
      image: confluentinc/cp-kafka:latest
      container_name: payment-charge-queue
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: 'payment-charge.events:3:1:1'
      volumes:
        - .docker-volumes/kafka:/data/db
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
        - payment-charge

    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: "payment-charge-kafka-ui"
      ports:
        - "8082:8080"
      networks:
        - payment-charge
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

networks:
    payment-charge:
        name: 'payment-charge'
